# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

    
steps:

- task: NodeTool@0
  inputs:
    versionSpec: '8.9.4'

- task: Npm@1
  displayName: 'Install dependencies (npm install)'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Running tests (npm test)'
  inputs:
    command: custom
    customCommand: 'test'

- script: npm run build 
  displayName: 'Building code (DEV)'

- task: CopyFiles@2
  inputs:
    contents: 'dist/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false