# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

    
steps:

- task: NodeTool@0
  inputs:
    versionSpec: '8.9.4'

- script: yarn install
  displayName: 'Install dependencies'

- script: yarn test
  displayName: 'Run tests'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
  # displayName: 'Run a multi-line script'


# - task: Npm@1
#   displayName: 'yarn install'
#   inputs:
#     command: install

# - task: Npm@1
#   displayName: 'yarn test'
#   inputs:
#     command: custom
#     customCommand: 'test'